Mongodb memory connector initial
BorisDog/semantic-kernel pull request #1
Opened 2023-09-19 23:04 UTC by BorisDog

### Motivation and Context

### Description

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

2023-09-20 22:43 UTC, JamesKovacs requested changes
This looks fantastic! Minor feedback inline.

2023-09-20 22:43 UTC, JamesKovacs commented on dotnet/MongoDbTest/Program.cs
> +const string connectionUri = "mongodb+srv://boris:Pas12345@cluster0.mqddkqg.mongodb.net/?retryWrites=true&w=majority";
Atlas credentials embedded in test code.

2023-09-20 22:43 UTC, JamesKovacs commented on dotnet/MongoDbTest/Program.cs
> +Console.WriteLine("Hello, World!");
Shouldn't this say something like "Starting test..." or similar?

2023-09-20 22:43 UTC, JamesKovacs commented on dotnet/MongoDbTest/Program.cs
> +var f = v.Select(f => (float)f).ToArray();
Why is the vector declared as an array of double but then the values cast to floats?

2023-09-20 22:43 UTC, JamesKovacs commented on dotnet/MongoDbTest/Program.cs
> +    .CosineSimilarity(f);
`similarity` and `similarity2` are identical. Why is it called twice?

2023-09-20 22:43 UTC, JamesKovacs commented on dotnet/samples/KernelSyntaxExamples/Example15_TextMemorySkill.cs
> +        //store = CreateSampleMongoDBMemoryStore();
Missing a space between `//` and `store`.

2023-09-20 22:43 UTC, JamesKovacs commented on dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoDBMemoryEntry.cs
> +        this.Embedding = memoryRecord.Embedding.ToArray();
Is `MemoryRecord.Embedding` guaranteed not to be null? I checked the docs and it doesn't say either way.

2023-09-21 00:48 UTC, BorisDog commented on dotnet/MongoDbTest/Program.cs
> +Console.WriteLine("Hello, World!");
Oh it's a leftover project I forgot to clean up.
Removed MongoDbTest. Thanks!

2023-09-21 00:48 UTC, BorisDog commented on dotnet/samples/KernelSyntaxExamples/Example15_TextMemorySkill.cs
> +        //store = CreateSampleMongoDBMemoryStore();
Tnx, done.

2023-09-21 00:48 UTC, BorisDog commented on dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoDBMemoryEntry.cs
> +        this.Embedding = memoryRecord.Embedding.ToArray();
Yes, it's type is `ReadonlyMemory<float>`, which is a struct.

2023-09-28 17:21 UTC, JamesKovacs approved these changes
LGTM

2023-09-28 21:01 UTC, closed without merging